name: Release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'Spectrum.zip'
        exclusions: '*.git* '
    - name: Create Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: "Spectrum.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
